version: '2'

networks:
  salary-hero-network:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - salary-hero-network
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    networks:
      - salary-hero-network
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin